#!/usr/bin/env node
/**
 * Vidius QA Risk Scanner — v0.2
 * Kullanım: node scan.js https://ornek-site.com [--pages=5]
 *
 * v0.1'e göre farklar:
 *  - Sadece anasayfa değil, siteden bulunan iç linklerle çoklu sayfa tarama
 *  - Masaüstü + mobil ekran görüntüsü (rapora gömülü)
 *  - Gerçek form testi (boş submit denemesi)
 *  - QA Sağlık Skoru (0-100) ve yönetici özeti
 *  - Ek SEO/teknik kontroller: H1 sayısı, canonical, robots.txt, sitemap.xml
 *  - Sayfa yükleme süresi
 */

const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const targetUrl = args.find(a => !a.startsWith('--'));
const pagesArg = args.find(a => a.startsWith('--pages='));
const MAX_PAGES = pagesArg ? parseInt(pagesArg.split('=')[1], 10) : 5;

if (!targetUrl) {
  console.error('Kullanım: node scan.js <url> [--pages=5]');
  process.exit(1);
}

const BUILDER_SIGNATURES = [
  { name: 'Lovable', pattern: /data-lov-id|lovable\.dev|lovable-tagger/i },
  { name: 'bolt.new / StackBlitz WebContainer', pattern: /bolt\.new|webcontainer/i },
  { name: 'v0.dev (Vercel)', pattern: /v0\.dev|generated by v0/i },
  { name: 'Framer AI', pattern: /framer\.com\/(m|ai)|data-framer/i },
  { name: 'Webflow', pattern: /webflow\.com|data-wf-/i },
  { name: 'Replit Agent', pattern: /replit\.(com|dev).*agent|replit-badge/i },
  { name: 'Base44', pattern: /base44/i },
  { name: 'Cursor/Windsurf config sızıntısı', pattern: /\.cursorrules|CLAUDE\.md|windsurfrules/i },
];

const SEVERITY_WEIGHT = { high: 15, medium: 7, low: 3, info: 0 };

// Büyük görsel eşikleri — sayfa performansı için pratik sınırlar
const IMAGE_SIZE_THRESHOLDS = { high: 1024 * 1024, medium: 300 * 1024 }; // 1MB / 300KB

function fmtBytes(bytes) {
  if (bytes >= 1024 * 1024) return `${(bytes / (1024 * 1024)).toFixed(1)}MB`;
  return `${Math.round(bytes / 1024)}KB`;
}

function escapeHtml(str) {
  return String(str).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
}

function sameDomain(a, b) {
  try { return new URL(a).hostname.replace('www.', '') === new URL(b).hostname.replace('www.', ''); }
  catch { return false; }
}

async function scanPage(context, url) {
  const findings = [];
  const consoleErrors = [];
  const failedRequests = [];
  const page = await context.newPage();

  page.on('console', msg => { if (msg.type() === 'error') consoleErrors.push(msg.text()); });
  page.on('requestfailed', req => failedRequests.push({ url: req.url(), failure: req.failure()?.errorText || 'bilinmiyor' }));

  const imageResponses = [];
  page.on('response', async (res) => {
    try {
      const req = res.request();
      if (req.resourceType() !== 'image') return;
      const headers = res.headers();
      let size = headers['content-length'] ? parseInt(headers['content-length'], 10) : null;
      if (size === null) {
        // content-length yoksa (ör. chunked/compressed), gövdeyi ölçmeyi dene
        const body = await res.body().catch(() => null);
        size = body ? body.length : null;
      }
      if (size !== null) imageResponses.push({ url: req.url(), size });
    } catch { /* bazı response'lar body okumaya kapalı olabilir, sessizce geç */ }
  });

  const startTime = Date.now();
  let response;
  try {
    response = await page.goto(url, { waitUntil: 'networkidle', timeout: 30000 });
  } catch (e) {
    findings.push({ severity: 'high', category: 'Erişim', text: `Sayfa yüklenemedi: ${e.message}` });
    await page.close();
    return { url, findings, loadTimeMs: null, links: [], screenshots: {} };
  }
  const loadTimeMs = Date.now() - startTime;

  const headers = response.headers();
  if (!url.startsWith('https://')) findings.push({ severity: 'high', category: 'Güvenlik', text: 'Sayfa HTTPS kullanmıyor.' });
  const secHeaders = ['strict-transport-security', 'x-content-type-options', 'x-frame-options', 'content-security-policy'];
  const missingHeaders = secHeaders.filter(h => !headers[h]);
  if (missingHeaders.length) findings.push({ severity: 'medium', category: 'Güvenlik', text: `Eksik güvenlik header'ları: ${missingHeaders.join(', ')}` });

  if (consoleErrors.length) findings.push({ severity: 'high', category: 'JS Hataları', text: `${consoleErrors.length} konsol hatası.`, detail: consoleErrors.slice(0, 8) });
  if (failedRequests.length) findings.push({ severity: 'high', category: 'Kırık Kaynaklar', text: `${failedRequests.length} kaynak yüklenemedi.`, detail: failedRequests.slice(0, 8).map(f => `${f.url} — ${f.failure}`) });

  if (loadTimeMs > 5000) findings.push({ severity: 'medium', category: 'Performans', text: `Sayfa yüklenmesi ${(loadTimeMs / 1000).toFixed(1)} saniye sürdü (5sn üzeri yavaş kabul edilir).` });

  // Optimize edilmemiş görseller
  const bigImages = imageResponses
    .filter(img => img.size >= IMAGE_SIZE_THRESHOLDS.medium)
    .sort((a, b) => b.size - a.size);
  const highImages = bigImages.filter(img => img.size >= IMAGE_SIZE_THRESHOLDS.high);
  const mediumImages = bigImages.filter(img => img.size < IMAGE_SIZE_THRESHOLDS.high);
  if (highImages.length) {
    findings.push({
      severity: 'high',
      category: 'Görsel Optimizasyonu',
      text: `${highImages.length} görsel 1MB üzerinde — sayfa hızını doğrudan etkiliyor.`,
      detail: highImages.slice(0, 8).map(img => `${fmtBytes(img.size)} — ${img.url}`),
    });
  }
  if (mediumImages.length) {
    findings.push({
      severity: 'medium',
      category: 'Görsel Optimizasyonu',
      text: `${mediumImages.length} görsel 300KB-1MB arası — sıkıştırılabilir.`,
      detail: mediumImages.slice(0, 8).map(img => `${fmtBytes(img.size)} — ${img.url}`),
    });
  }

  const title = await page.title();
  const metaDesc = await page.$eval('meta[name="description"]', el => el.content).catch(() => null);
  const canonical = await page.$eval('link[rel="canonical"]', el => el.href).catch(() => null);
  const h1Count = await page.$$eval('h1', els => els.length).catch(() => 0);
  if (!title) findings.push({ severity: 'medium', category: 'SEO', text: 'Title etiketi boş/yok.' });
  if (!metaDesc) findings.push({ severity: 'low', category: 'SEO', text: 'Meta description yok.' });
  if (!canonical) findings.push({ severity: 'low', category: 'SEO', text: 'Canonical tag yok.' });
  if (h1Count === 0) findings.push({ severity: 'medium', category: 'SEO', text: 'Sayfada H1 etiketi yok.' });
  if (h1Count > 1) findings.push({ severity: 'low', category: 'SEO', text: `Sayfada ${h1Count} adet H1 var (idealde 1 tane olmalı).` });

  const imgsMissingAlt = await page.$$eval('img', imgs => imgs.filter(i => !i.alt || i.alt.trim() === '').length);
  if (imgsMissingAlt > 0) findings.push({ severity: 'medium', category: 'Erişilebilirlik', text: `${imgsMissingAlt} görselde alt metni eksik.` });

  const inputsMissingLabel = await page.$$eval('input:not([type=hidden])', inputs =>
    inputs.filter(i => !i.getAttribute('aria-label') && !(i.id && document.querySelector(`label[for="${i.id}"]`)) && !i.closest('label')).length
  ).catch(() => 0);
  if (inputsMissingLabel > 0) findings.push({ severity: 'medium', category: 'Erişilebilirlik', text: `${inputsMissingLabel} form alanında label eksik.` });

  await page.setViewportSize({ width: 375, height: 812 });
  await page.waitForTimeout(400);
  const hasOverflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 5);
  if (hasOverflow) findings.push({ severity: 'medium', category: 'Mobil/Responsive', text: 'Mobilde (375px) yatay taşma var.' });
  const mobileShot = await page.screenshot({ fullPage: false }).catch(() => null);

  await page.setViewportSize({ width: 1280, height: 800 });
  await page.waitForTimeout(300);
  const desktopShot = await page.screenshot({ fullPage: false }).catch(() => null);

  const formResults = await page.$$eval('form', forms =>
    forms.map(f => {
      const requiredFields = f.querySelectorAll('[required]').length;
      const submitBtn = f.querySelector('button[type=submit], input[type=submit], button:not([type])');
      let validationTriggered = null;
      if (requiredFields > 0 && submitBtn) {
        submitBtn.click();
        validationTriggered = !f.checkValidity();
      }
      return { requiredFields, hasSubmitButton: !!submitBtn, validationTriggered };
    })
  ).catch(() => []);
  formResults.forEach((f, i) => {
    if (f.requiredFields > 0 && f.validationTriggered === false) {
      findings.push({ severity: 'high', category: 'Form Validasyonu', text: `Form #${i + 1}: zorunlu alanlar var ama boş submit engellenmedi.` });
    } else if (f.requiredFields === 0 && f.hasSubmitButton) {
      findings.push({ severity: 'low', category: 'Form Validasyonu', text: `Form #${i + 1}: hiçbir alan "required" olarak işaretlenmemiş.` });
    }
  });

  const html = await page.content();
  const builderHits = BUILDER_SIGNATURES.filter(sig => sig.pattern.test(html));
  if (builderHits.length) {
    findings.push({ severity: 'info', category: 'Olası AI/No-Code Sinyali (KANIT DEĞİL)', text: `İzler bulundu: ${builderHits.map(b => b.name).join(', ')}. Bu kesin kanıt değildir, sadece olasılık belirtir.` });
  }

  const links = await page.$$eval('a[href]', as => Array.from(new Set(as.map(a => a.href))).filter(h => h.startsWith('http')));

  await page.close();
  return { url, findings, loadTimeMs, links, screenshots: { desktop: desktopShot, mobile: mobileShot }, builderHits };
}

async function checkRobotsAndSitemap(context, baseUrl) {
  const findings = [];
  const origin = new URL(baseUrl).origin;
  try {
    const robots = await context.request.get(`${origin}/robots.txt`, { timeout: 8000 });
    if (robots.status() >= 400) findings.push({ severity: 'low', category: 'Teknik SEO', text: 'robots.txt bulunamadı.' });
  } catch { findings.push({ severity: 'low', category: 'Teknik SEO', text: 'robots.txt kontrol edilemedi.' }); }
  try {
    const sitemap = await context.request.get(`${origin}/sitemap.xml`, { timeout: 8000 });
    if (sitemap.status() >= 400) findings.push({ severity: 'low', category: 'Teknik SEO', text: 'sitemap.xml bulunamadı.' });
  } catch { findings.push({ severity: 'low', category: 'Teknik SEO', text: 'sitemap.xml kontrol edilemedi.' }); }
  return findings;
}

async function checkBrokenLinks(context, links) {
  const broken = [];
  for (const link of links.slice(0, 30)) {
    try {
      let res = await context.request.head(link, { timeout: 8000 });
      if (res.status() === 405) res = await context.request.get(link, { timeout: 8000 });
      if (res.status() >= 400) broken.push({ url: link, status: res.status() });
    } catch { broken.push({ url: link, status: 'zaman aşımı/erişilemedi' }); }
  }
  return broken;
}

function calcScore(allFindings) {
  let score = 100;
  allFindings.forEach(f => { score -= SEVERITY_WEIGHT[f.severity] || 0; });
  return Math.max(0, Math.round(score));
}

async function run() {
  const browser = await chromium.launch();
  const context = await browser.newContext();

  console.log(`Taranıyor: ${targetUrl} (en fazla ${MAX_PAGES} sayfa)`);
  const visited = new Set();
  const toVisit = [targetUrl];
  const pageResults = [];

  while (toVisit.length && pageResults.length < MAX_PAGES) {
    const url = toVisit.shift();
    if (visited.has(url)) continue;
    visited.add(url);
    console.log(`  → ${url}`);
    const result = await scanPage(context, url);
    pageResults.push(result);
    if (pageResults.length === 1) {
      const broken = await checkBrokenLinks(context, result.links);
      if (broken.length) result.findings.push({ severity: 'high', category: 'Kırık Linkler', text: `${broken.length} link hatalı döndü.`, detail: broken.map(b => `${b.url} — ${b.status}`) });
      const techFindings = await checkRobotsAndSitemap(context, targetUrl);
      result.findings.push(...techFindings);
    }
    result.links.filter(l => sameDomain(l, targetUrl) && !visited.has(l) && !toVisit.includes(l)).forEach(l => toVisit.push(l));
  }

  await writeReport(targetUrl, pageResults);
  await browser.close();
}

async function writeReport(targetUrl, pageResults) {
  const outDir = path.join(__dirname, 'reports');
  const safeName = targetUrl.replace(/https?:\/\//, '').replace(/[^a-z0-9]/gi, '_').slice(0, 50);
  const stamp = Date.now();
  const reportDir = path.join(outDir, `${safeName}_${stamp}`);
  fs.mkdirSync(reportDir, { recursive: true });

  const allFindings = pageResults.flatMap(p => p.findings);
  const score = calcScore(allFindings);
  const grouped = { high: allFindings.filter(f => f.severity === 'high'), medium: allFindings.filter(f => f.severity === 'medium'), low: allFindings.filter(f => f.severity === 'low'), info: allFindings.filter(f => f.severity === 'info') };
  const builderHits = [...new Set(pageResults.flatMap(p => p.builderHits || []).map(b => b.name))];

  pageResults.forEach((p, i) => {
    if (p.screenshots?.desktop) fs.writeFileSync(path.join(reportDir, `p${i}_desktop.png`), p.screenshots.desktop);
    if (p.screenshots?.mobile) fs.writeFileSync(path.join(reportDir, `p${i}_mobile.png`), p.screenshots.mobile);
  });

  const scoreColor = score >= 80 ? '#2e9e4a' : score >= 50 ? '#e0a11a' : '#d64545';
  const sevLabel = { high: 'Yüksek', medium: 'Orta', low: 'Düşük', info: 'Bilgi' };
  const sevColor = { high: '#d64545', medium: '#e0a11a', low: '#3a7bd5', info: '#7a7a7a' };

  const summaryText = `${pageResults.length} sayfa tarandı. Toplam ${allFindings.length} bulgu tespit edildi ` +
    `(${grouped.high.length} yüksek, ${grouped.medium.length} orta, ${grouped.low.length} düşük öncelikli). ` +
    (builderHits.length ? `Sayfa kaynağında ${builderHits.join(', ')} araçlarına ait izler görüldü (olası AI/no-code kullanım sinyali, kanıt değil). ` : '') +
    (grouped.high.length > 0 ? `Özellikle ${grouped.high.length} adet yüksek öncelikli bulgu, canlı ortamda kullanıcı deneyimini doğrudan etkileyen sorunlara işaret ediyor.` : 'Yüksek öncelikli kritik bir sorun görülmedi.');

  const pageSection = (p, i) => {
    const g = { high: p.findings.filter(f => f.severity === 'high'), medium: p.findings.filter(f => f.severity === 'medium'), low: p.findings.filter(f => f.severity === 'low'), info: p.findings.filter(f => f.severity === 'info') };
    const list = (sev) => g[sev].length ? `<h4 style="color:${sevColor[sev]};margin-bottom:4px">${sevLabel[sev]} (${g[sev].length})</h4><ul>${g[sev].map(f => `<li><strong>[${f.category}]</strong> ${escapeHtml(f.text)}${f.detail ? `<ul>${f.detail.map(d => `<li><code>${escapeHtml(d)}</code></li>`).join('')}</ul>` : ''}</li>`).join('')}</ul>` : '';
    return `
    <div class="page-block">
      <h3>${i + 1}. ${escapeHtml(p.url)}</h3>
      <div class="meta">${p.loadTimeMs !== null ? `Yükleme süresi: ${(p.loadTimeMs / 1000).toFixed(2)} sn — ` : ''}${p.findings.length} bulgu</div>
      ${p.screenshots?.desktop ? `
      <div class="shots">
        <div><img src="p${i}_desktop.png" alt="masaüstü görünüm"><div class="cap">Masaüstü</div></div>
        ${p.screenshots?.mobile ? `<div><img src="p${i}_mobile.png" class="mobile-shot" alt="mobil görünüm"><div class="cap">Mobil</div></div>` : ''}
      </div>` : ''}
      ${list('high')}${list('medium')}${list('low')}${list('info')}
      ${p.findings.length === 0 ? '<p>Bu sayfada kayda değer bir sorun bulunamadı.</p>' : ''}
    </div>`;
  };

  const reportHtml = `<!DOCTYPE html>
<html lang="tr"><head><meta charset="UTF-8">
<title>QA Risk Raporu — ${escapeHtml(targetUrl)}</title>
<style>
  body { font-family: -apple-system, Segoe UI, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #222; line-height: 1.5; }
  h1 { font-size: 24px; margin-bottom: 4px; } h2 { border-bottom: 2px solid #eee; padding-bottom: 6px; margin-top: 36px; }
  .meta { color: #666; font-size: 13px; }
  .disclaimer { background: #fff8e1; border: 1px solid #f0d878; border-radius: 6px; padding: 12px 16px; font-size: 14px; margin: 20px 0; }
  .exec-summary { display: flex; gap: 24px; align-items: center; background: #fafafa; border-radius: 10px; padding: 20px; margin: 20px 0; }
  .score-circle { flex-shrink: 0; width: 110px; height: 110px; border-radius: 50%; border: 8px solid ${scoreColor}; display: flex; align-items: center; justify-content: center; font-size: 32px; font-weight: bold; color: ${scoreColor}; }
  .exec-text { font-size: 15px; }
  .page-block { border: 1px solid #eee; border-radius: 8px; padding: 16px 20px; margin-bottom: 20px; }
  .shots { display: flex; gap: 12px; margin: 12px 0; }
  .shots img { border: 1px solid #ddd; border-radius: 4px; }
  .shots img.mobile-shot { max-height: 300px; }
  .shots img:not(.mobile-shot) { max-width: 480px; max-height: 300px; object-fit: cover; object-position: top; }
  .cap { text-align: center; font-size: 12px; color: #888; }
  code { background: #f4f4f4; padding: 1px 4px; border-radius: 3px; font-size: 13px; }
  li { margin-bottom: 5px; }
</style></head>
<body>
  <h1>QA Risk Raporu</h1>
  <div class="meta">Hedef: <strong>${escapeHtml(targetUrl)}</strong> — Tarih: ${new Date().toLocaleString('tr-TR')} — ${pageResults.length} sayfa tarandı</div>

  <div class="exec-summary">
    <div class="score-circle">${score}</div>
    <div class="exec-text"><strong>QA Sağlık Skoru: ${score}/100</strong><br>${summaryText}</div>
  </div>

  <div class="disclaimer">Bu rapor otomatik bir tarama sonucudur. "AI/No-Code Sinyali" bulguları kesin kanıt değildir — yalnızca olasılık belirtir. Diğer bulgular (konsol hataları, kırık linkler, erişilebilirlik, form validasyonu) doğrudan gözlemlenmiş, kanıtlanabilir sorunlardır. Kapsamlı manuel/exploratory testin yerini tutmaz.</div>

  <h2>Sayfa Bazlı Bulgular</h2>
  ${pageResults.map((p, i) => pageSection(p, i)).join('')}
</body></html>`;

  const outPath = path.join(reportDir, 'rapor.html');
  fs.writeFileSync(outPath, reportHtml, 'utf-8');
  console.log(`\n✅ Rapor oluşturuldu: ${outPath}`);
  console.log(`   QA Sağlık Skoru: ${score}/100 — Toplam bulgu: ${allFindings.length}`);
}

run().catch(e => { console.error('Beklenmeyen hata:', e); process.exit(1); });
